#!/bin/bash

# IBS: Intelligent Bandwidth Shifting scheduler implementation.
# Copyright (C) 2020  Manel Lurbe Sempere <malursem@inf.upv.es>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo ''
echo 'IBS implementation Copyright (C) 2020 Manel Lurbe Sempere <malursem@inf.upv.es>.'
echo 'This program comes with ABSOLUTELY NO WARRANTY; for details type show w.'
echo 'This is free software, and you are welcome to redistribute it under certain conditions type show c for details.'
echo ''

helpFunction()
{
   echo ""
   echo "Usage: $0 -a workloadArray -b dirOut"
   echo -e "\t-a workloadArray benchmaks workload to be executed. Posibilities:"
   echo -e "\t\ta: 6 apps workloads"
   echo -e "\t\tb: 8 apps workloads"
   echo -e "\t\tc: 10 app workloads"
   echo -e "\t\td: validation workloads"
   echo -e "\t-b dirOut is the output directory."
   exit 1 # Exit script after printing help
}

# Get the arguments
while getopts "a:b:c:" opt
do
   case "$opt" in
      a ) ARRAY="$OPTARG" ;;
      b ) DIROUT="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "$ARRAY" ] || [ -z "$DIROUT" ]
then
   echo "Missing arguments.";
   helpFunction
fi

if mkdir IBS_res/${DIROUT} ; then
    echo \#Directory created working_dir/IBS_res/${DIROUT}\#
else
    echo ""
    echo \#Error creating directory working_dir/IBS_res/${DIROUT}\#
    echo \#The directory may already exist\#
    echo ""
fi


# Select the array of benckmarks to be executed
case "$ARRAY" in
   #case 1
   "a") workloadArray="2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23";;## 6 applications workload.
      
   #case 2 
   "b") workloadArray="24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39" ;;# 8 applications workload.

   #case 3 
   "c") workloadArray="40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55" ;;## 10 applications workload.

   #case 4 
   "d") workloadArray="56 57 58 59 60 61" ;;## Validation workloads.
   #case 5 
   *) echo "Invalid entry for workloadArray."
      helpFunction;; 
esac

{ ./start_Experiments.sh; }

for workload in $workloadArray
do
      sudo ./IBS -A $workload -o "/home/malursem/working_dir/IBS_res/${DIROUT}/trabajo[${workload}]conf[ibs].txt" -F -Q 2>> /home/malursem/working_dir/IBS_res/${DIROUT}/stderr_trabajo[${workload}]conf[ibs].txt
done;

{ ./end_Experiments.sh; }
