#!/bin/bash

# IBS: Intelligent Bandwidth Shifting scheduler implementation.
# Copyright (C) 2020  Manel Lurbe Sempere <malursem@inf.upv.es>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rm -rf ../working_dir/libpfm-4.10.1/perf_examples/IBS*

if cp Makefile IBS.c ../working_dir/libpfm-4.10.1/perf_examples/ ; then
	if cd ../working_dir/libpfm-4.10.1/perf_examples/ ; then
		if make ; then
			if cp -rf IBS ../../ ; then
				echo "Proceso terminado correctamente."
			else
				echo "Error al copiar los programas."
			fi
		else
			echo "Error al compilar el programa."
		fi
	else
		echo "Error al cambiar de directorio."
	fi
else
	echo "Error de copia de los ficheros."
fi
